export const itemsData = [
  {
    date: " 1/2021",
    printerId: "",
    location: {
      facility: "",
      department: "",
      room: "",
    },
    frequency: 80,
    totalA3Pages: 50,
    totalA4Pages: 100,
    printed: 10,
  },
  {
    date: " 1/2021",
    printerId: "",
    location: {
      facility: "",
      department: "",
      room: "",
    },
    frequency: 80,
    totalA3Pages: 50,
    totalA4Pages: 100,
    printed: 10,
  },
  {
    date: " 1/2021",
    printerId: "",
    location: {
      facility: "",
      department: "",
      room: "",
    },
    frequency: 80,
    totalA3Pages: 50,
    totalA4Pages: 100,
    printed: 10,
  },
  {
    date: " 1/2021",
    printerId: "",
    location: {
      facility: "",
      department: "",
      room: "",
    },
    frequency: 80,
    totalA3Pages: 50,
    totalA4Pages: 100,
    printed: 10,
  },
  {
    date: " 1/2021",
    printerId: "",
    location: {
      facility: "",
      department: "",
      room: "",
    },
    frequency: 80,
    totalA3Pages: 50,
    totalA4Pages: 100,
    printed: 10,
  },
  {
    date: " 1/2021",
    printerId: "",
    location: {
      facility: "",
      department: "",
      room: "",
    },
    frequency: 80,
    totalA3Pages: 50,
    totalA4Pages: 100,
    printed: 10,
  },
];
