export const activities = [
  {
    studentName: "",
    studentId: "...",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "...",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
  {
    studentName: "",
    studentId: "",
    classes: "",
    totlePages: 0,
    major: "",
    history: [
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
      {
        date: "",
        fileNames: "",
        quantity: 0,
        page_Quantity: { A4: 0, A3: 0 },
      },
    ],
  },
];
